HOST: http://rcswitch.apiary.io/

--- rc-switch-rest ---

---
Welcome to the RESTful API for the rc-switch library. With this API you can operate your radio-controlled switches. 
You can find the library to access the switches with your Rasperry PI [here](http://github.com/denschu/rc-switch). 
---

--
RC Switch Resources
The following is a section of resources related to the switches.
--

List available switches
GET /switches
< 200
< Content-Type: application/json
[
{ "id": "0", "url": "/switches/0", "name": "Lamp 1", "script": "sudo /home/pi/rcswitch-pi/sendRev", "command": "B 1", "status": "0"},
{ "id": "1", "url": "/switches/1", "name": "Lamp 2", "script": "sudo /home/pi/rcswitch-pi/send", "command": "11111 1", "status": "0"}
]

Get switch
GET /switches/0
< 200
< Content-Type: application/json
{ "id": "0", "url": "/switches/0", "name": "Lamp 1", "script": "sudo /home/pi/rcswitch-pi/sendRev", "command": "B 1", "status": "0"}

Save new switch configurations
POST /switches
> Content-Type: application/json
{ "name": "Lamp 1", "script": "sudo /home/pi/rcswitch-pi/sendRev", "command":"B 1" }
< 201

Update switch status
PUT /switches/0
> Content-Type: application/json
{ "status": "1" }
< 200

Delete switch configuration
DELETE /switches/0
> Content-Type: application/json
{ "id": "0" }
< 200